[package]
name = "rustats"
version = "0.1.234"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustats"
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.16.1"
numpy = "0.25.0"
pyo3 = "0.25.0"
