import numpy as np

type Array2D = np.ndarray[tuple[int, int], np.dtype[np.float32]]

def move_max(array: Array2D, length: int, min_length: int) -> Array2D:
    ...
def move_min(array: Array2D, length: int, min_length: int) -> Array2D:
    ...
def move_median(array: Array2D, length: int, min_length: int) -> Array2D:
    ...
def move_median_old(array: Array2D, length: int, min_length: int) -> Array2D:
    ...